name: Build

on:
  workflow_dispatch:

jobs:
  job_name:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'terraform/environments/dev'

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: brianpham
          password: ${{ secrets.GH_PAT_TOKEN }}

      - name: Get Git Tag
        id: git_tag
        run: |
          echo "Getting tags from $GITHUB_REF"
          export TAG=`git rev-parse --short HEAD `
          echo "Tag will be $TAG"
          echo ::set-output name=tag::${TAG}

      - name: Build Static App Image
        uses: docker/build-push-action@v3
        with:
          context: ./static-app
          push: true
          tags: ghcr.io/brianpham/supersimpleapp:${{ steps.git_tag.outputs.TAG }}

      - name: Build Info
        run: |
          echo "Image have been built and pushed successfully."
          echo "ghcr.io/brianpham/supersimpleapp:${{ steps.git_tag.outputs.TAG }}"